"""xnlogo runtime - NetLogo primitives and execution environment."""

from xnlogo.runtime.api import (
    # Model Entry Point
    Model,
    # UI Widgets
    UIWidget,
    View,
    Button,
    Monitor,
    Switch,
    Slider,
    Plot,
    PlotPen,
    TextBox,
    # Model Structure
    globals,
    Globals,
    breed,
    Breed,
    world,
    World,
    observer,
    turtle,
    patch,
    # Core API (deprecated)
    agent,
    run,
    # Pythonic API
    AgentSet,
    Agent,
    me,
    create_turtles,
    randomly_distribute,
    every_patch,
    every_turtle,
    # World Control
    clear_all,
    clear_turtles,
    clear_patches,
    clear_drawing,
    reset_ticks,
    tick,
    ticks,
    # Agentsets
    turtles,
    patches,
    links,
    breed_agentset,
    other,
    self_agent,
    myself,
    # Selection
    n_of,
    one_of,
    max_one_of,
    min_one_of,
    max_n_of,
    min_n_of,
    with_expr,
    # Queries
    count,
    any_agents,
    all_agents,
    # Commands
    ask,
    sprout,
    hatch,
    die,
    # Movement
    forward,
    fd,
    back,
    bk,
    left,
    lt,
    right,
    rt,
    face,
    facexy,
    setxy,
    move_to,
    # Patch Navigation
    patch_here,
    patch_at,
    patch_ahead,
    neighbors,
    neighbors4,
    # Spatial Queries
    in_radius,
    in_cone,
    distance,
    towards,
    distance_xy,
    towards_xy,
    # Turtle Queries
    xcor,
    ycor,
    heading,
    color,
    size,
    shape,
    label,
    hidden,
    # Patch Queries
    pxcor,
    pycor,
    pcolor,
    plabel,
    # World Queries
    max_pxcor,
    max_pycor,
    min_pxcor,
    min_pycor,
    world_width,
    world_height,
    # Setters
    set_color,
    set_heading,
    set_size,
    set_shape,
    set_label,
    set_pcolor,
    set_plabel,
    set_var,
    # Random
    random,
    random_float,
    random_int,
    random_xcor,
    random_ycor,
    random_pxcor,
    random_pycor,
    # Links
    create_link_to,
    create_link_from,
    create_links_to,
    create_links_from,
    my_links,
    my_in_links,
    my_out_links,
    link_neighbors,
    in_link_neighbors,
    out_link_neighbors,
    # Colors
    scale_color,
    shade_of,
    # Math
    abs_val,
    acos,
    asin,
    atan,
    cos,
    sin,
    tan,
    exp,
    ln,
    log,
    sqrt,
    ceiling,
    floor,
    round_val,
    precision,
    remainder,
    mod,
    # Lists
    length,
    item,
    first,
    last,
    but_first,
    but_last,
    empty,
    member,
    position,
    remove,
    remove_duplicates,
    reverse,
    sort,
    shuffle,
    # Type Checks
    is_string,
    is_number,
    is_boolean,
    is_list,
    is_agent,
    is_agentset,
    is_patch,
    is_turtle,
    is_link,
    # I/O
    print_msg,
    show,
    write,
    type_msg,
    # Timing
    timer,
    reset_timer,
    # Display
    display,
    no_display,
    # String
    word,
)

__all__ = [
    # Model Entry Point
    "Model",
    # UI Widgets
    "UIWidget",
    "View",
    "Button",
    "Monitor",
    "Switch",
    "Slider",
    "Plot",
    "PlotPen",
    "TextBox",
    # Model Structure
    "globals",
    "Globals",
    "breed",
    "Breed",
    "world",
    "World",
    "observer",
    "turtle",
    "patch",
    # Core API
    "agent",
    "run",
    # Pythonic API
    "AgentSet",
    "Agent",
    "me",
    "create_turtles",
    "randomly_distribute",
    "every_patch",
    "every_turtle",
    # World Control
    "clear_all",
    "clear_turtles",
    "clear_patches",
    "clear_drawing",
    "reset_ticks",
    "tick",
    "ticks",
    # Agentsets
    "turtles",
    "patches",
    "links",
    "breed_agentset",
    "other",
    "self_agent",
    "myself",
    # Selection
    "n_of",
    "one_of",
    "max_one_of",
    "min_one_of",
    "max_n_of",
    "min_n_of",
    "with_expr",
    # Queries
    "count",
    "any_agents",
    "all_agents",
    # Commands
    "ask",
    "sprout",
    "hatch",
    "die",
    # Movement
    "forward",
    "fd",
    "back",
    "bk",
    "left",
    "lt",
    "right",
    "rt",
    "face",
    "facexy",
    "setxy",
    "move_to",
    # Patch Navigation
    "patch_here",
    "patch_at",
    "patch_ahead",
    "neighbors",
    "neighbors4",
    # Spatial Queries
    "in_radius",
    "in_cone",
    "distance",
    "towards",
    "distance_xy",
    "towards_xy",
    # Turtle Queries
    "xcor",
    "ycor",
    "heading",
    "color",
    "size",
    "shape",
    "label",
    "hidden",
    # Patch Queries
    "pxcor",
    "pycor",
    "pcolor",
    "plabel",
    # World Queries
    "max_pxcor",
    "max_pycor",
    "min_pxcor",
    "min_pycor",
    "world_width",
    "world_height",
    # Setters
    "set_color",
    "set_heading",
    "set_size",
    "set_shape",
    "set_label",
    "set_pcolor",
    "set_plabel",
    "set_var",
    # Random
    "random",
    "random_float",
    "random_int",
    "random_xcor",
    "random_ycor",
    "random_pxcor",
    "random_pycor",
    # Links
    "create_link_to",
    "create_link_from",
    "create_links_to",
    "create_links_from",
    "my_links",
    "my_in_links",
    "my_out_links",
    "link_neighbors",
    "in_link_neighbors",
    "out_link_neighbors",
    # Colors
    "scale_color",
    "shade_of",
    # Math
    "abs_val",
    "acos",
    "asin",
    "atan",
    "cos",
    "sin",
    "tan",
    "exp",
    "ln",
    "log",
    "sqrt",
    "ceiling",
    "floor",
    "round_val",
    "precision",
    "remainder",
    "mod",
    # Lists
    "length",
    "item",
    "first",
    "last",
    "but_first",
    "but_last",
    "empty",
    "member",
    "position",
    "remove",
    "remove_duplicates",
    "reverse",
    "sort",
    "shuffle",
    # Type Checks
    "is_string",
    "is_number",
    "is_boolean",
    "is_list",
    "is_agent",
    "is_agentset",
    "is_patch",
    "is_turtle",
    "is_link",
    # I/O
    "print_msg",
    "show",
    "write",
    "type_msg",
    # Timing
    "timer",
    "reset_timer",
    # Display
    "display",
    "no_display",
    # String
    "word",
]
